// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VolleyballIS.Infrastructure.Data;

#nullable disable

namespace VolleyballIS.Infrastructure.Migrations
{
    [DbContext(typeof(VolleyballDbContext))]
    [Migration("20260526223429_AddBestOf3Support")]
    partial class AddBestOf3Support
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VolleyballIS.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasColumnType("text")
                        .HasColumnName("full_name");

                    b.Property<int?>("LinkedCoachId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_coach_id");

                    b.Property<int?>("LinkedOrganizerId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_organizer_id");

                    b.Property<int?>("LinkedPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_player_id");

                    b.Property<int?>("LinkedRefereeId")
                        .HasColumnType("integer")
                        .HasColumnName("linked_referee_id");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LinkedCoachId");

                    b.HasIndex("LinkedOrganizerId");

                    b.HasIndex("LinkedPlayerId");

                    b.HasIndex("LinkedRefereeId");

                    b.ToTable("app_users", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.R1StartingLineup", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<short>("PositionNo")
                        .HasColumnType("smallint")
                        .HasColumnName("position_no");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("MatchId", "TeamId", "SetNumber", "PositionNo");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchId", "TeamId", "SetNumber", "PlayerId")
                        .IsUnique();

                    b.ToTable("r1_starting_lineups", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.R2PlayerStats", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<short>("Aces")
                        .HasColumnType("smallint")
                        .HasColumnName("aces");

                    b.Property<short>("AttackErrors")
                        .HasColumnType("smallint")
                        .HasColumnName("attack_errors");

                    b.Property<short>("AttackPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("attack_points");

                    b.Property<short>("AttacksTotal")
                        .HasColumnType("smallint")
                        .HasColumnName("attacks_total");

                    b.Property<short>("Blocks")
                        .HasColumnType("smallint")
                        .HasColumnName("blocks");

                    b.Property<short>("PositiveReceptions")
                        .HasColumnType("smallint")
                        .HasColumnName("positive_receptions");

                    b.Property<short>("ReceptionErrors")
                        .HasColumnType("smallint")
                        .HasColumnName("reception_errors");

                    b.Property<short>("ReceptionsTotal")
                        .HasColumnType("smallint")
                        .HasColumnName("receptions_total");

                    b.Property<short>("ServeErrors")
                        .HasColumnType("smallint")
                        .HasColumnName("serve_errors");

                    b.Property<short>("ServesTotal")
                        .HasColumnType("smallint")
                        .HasColumnName("serves_total");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<short>("TotalPoints")
                        .HasColumnType("smallint")
                        .HasColumnName("total_points");

                    b.HasKey("MatchId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("r2_player_stats", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.R3Set", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<short?>("DurationMin")
                        .HasColumnType("smallint")
                        .HasColumnName("duration_min");

                    b.Property<short?>("GuestScore")
                        .HasColumnType("smallint")
                        .HasColumnName("guest_score");

                    b.Property<short?>("HomeScore")
                        .HasColumnType("smallint")
                        .HasColumnName("home_score");

                    b.HasKey("MatchId", "SetNumber");

                    b.ToTable("r3_sets", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S10SubstitutionType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s10_substitution_types", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S11TimeoutType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s11_timeout_types", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S12SanctionType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s12_sanction_types", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S13DelayViolation", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s13_delay_violations", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S14AwardType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s14_award_types", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S15SanctionKind", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s15_sanction_kinds", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S16RecipientType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s16_recipient_types", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S17CoinTossOption", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s17_coin_toss_options", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S18ScoringSystem", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<short>("PointsLoss03")
                        .HasColumnType("smallint")
                        .HasColumnName("points_loss_0_3");

                    b.Property<short>("PointsLoss13")
                        .HasColumnType("smallint")
                        .HasColumnName("points_loss_1_3");

                    b.Property<short>("PointsLoss23")
                        .HasColumnType("smallint")
                        .HasColumnName("points_loss_2_3");

                    b.Property<short>("PointsWin30")
                        .HasColumnType("smallint")
                        .HasColumnName("points_win_3_0");

                    b.Property<short>("PointsWin31")
                        .HasColumnType("smallint")
                        .HasColumnName("points_win_3_1");

                    b.Property<short>("PointsWin32")
                        .HasColumnType("smallint")
                        .HasColumnName("points_win_3_2");

                    b.HasKey("Code");

                    b.ToTable("s18_scoring_systems", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S1Amplua", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s1_amplua", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S2PlayerStatus", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s2_player_statuses", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S3ApplicationStatus", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s3_application_statuses", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S4TournamentFormat", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s4_tournament_formats", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S5TournamentStage", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s5_tournament_stages", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S6MatchStatus", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s6_match_statuses", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S7ProtocolStatus", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s7_protocol_statuses", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S8RefereeRole", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s8_referee_roles", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.S9EventType", b =>
                {
                    b.Property<short>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasColumnName("code");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<short>("Code"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsTeamEvent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_team_event");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Code");

                    b.ToTable("s9_event_types", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T10Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AgeCategory")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("age_category");

                    b.Property<DateOnly?>("ApplicationDeadline")
                        .HasColumnType("date")
                        .HasColumnName("application_deadline");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<short>("FormatCode")
                        .HasColumnType("smallint")
                        .HasColumnName("format_code");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("gender");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("level");

                    b.Property<short>("MaxPlayersPerApp")
                        .HasColumnType("smallint")
                        .HasColumnName("max_players_per_app");

                    b.Property<short?>("MaxTeams")
                        .HasColumnType("smallint")
                        .HasColumnName("max_teams");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("integer")
                        .HasColumnName("organizer_id");

                    b.Property<short>("ScoringSystemCode")
                        .HasColumnType("smallint")
                        .HasColumnName("scoring_system_code");

                    b.Property<int?>("SeasonId")
                        .HasColumnType("integer")
                        .HasColumnName("season_id");

                    b.Property<short>("SetsToWin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)3)
                        .HasColumnName("sets_to_win");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<short>("TiebreakScoreTarget")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)15)
                        .HasColumnName("tiebreak_score_target");

                    b.HasKey("Id");

                    b.HasIndex("FormatCode");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OrganizerId");

                    b.HasIndex("ScoringSystemCode");

                    b.HasIndex("SeasonId");

                    b.ToTable("t10_tournaments", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T11Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Name")
                        .IsUnique();

                    b.ToTable("t11_groups", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T12Referee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("category");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("license_number");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("t12_referees", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T13Organizer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("t13_organizers", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T14Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("CoinTossChoiceCode")
                        .HasColumnType("smallint")
                        .HasColumnName("coin_toss_choice_code");

                    b.Property<int?>("CoinTossWinnerTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("coin_toss_winner_team_id");

                    b.Property<TimeOnly?>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<int?>("FirstServeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("first_serve_team_id");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer")
                        .HasColumnName("group_id");

                    b.Property<int>("GuestTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("guest_team_id");

                    b.Property<bool>("HasVideoChallenge")
                        .HasColumnType("boolean")
                        .HasColumnName("has_video_challenge");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer")
                        .HasColumnName("home_team_id");

                    b.Property<DateOnly>("MatchDate")
                        .HasColumnType("date")
                        .HasColumnName("match_date");

                    b.Property<decimal?>("NetHeight")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("net_height");

                    b.Property<short>("StageCode")
                        .HasColumnType("smallint")
                        .HasColumnName("stage_code");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.Property<string>("TechDefeatReason")
                        .HasColumnType("text")
                        .HasColumnName("tech_defeat_reason");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.Property<int>("VenueId")
                        .HasColumnType("integer")
                        .HasColumnName("venue_id");

                    b.HasKey("Id");

                    b.HasIndex("CoinTossChoiceCode");

                    b.HasIndex("CoinTossWinnerTeamId");

                    b.HasIndex("FirstServeTeamId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GuestTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("StageCode");

                    b.HasIndex("StatusCode");

                    b.HasIndex("TournamentId");

                    b.HasIndex("VenueId");

                    b.ToTable("t14_matches", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T15RefereeAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("LineJudgeSeqNo")
                        .HasColumnType("smallint")
                        .HasColumnName("line_judge_seq_no");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("RefereeId")
                        .HasColumnType("integer")
                        .HasColumnName("referee_id");

                    b.Property<short>("RoleCode")
                        .HasColumnType("smallint")
                        .HasColumnName("role_code");

                    b.HasKey("Id");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RoleCode");

                    b.HasIndex("MatchId", "RefereeId")
                        .IsUnique();

                    b.ToTable("t15_referee_assignments", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T16Protocol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("ApprovalDate")
                        .HasColumnType("date")
                        .HasColumnName("approval_date");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int?>("OrganizerId")
                        .HasColumnType("integer")
                        .HasColumnName("organizer_id");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .IsUnique();

                    b.HasIndex("OrganizerId");

                    b.HasIndex("StatusCode");

                    b.ToTable("t16_protocols", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T16ProtocolHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("changed_at");

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("DataHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("data_hash");

                    b.Property<int>("ProtocolId")
                        .HasColumnType("integer")
                        .HasColumnName("protocol_id");

                    b.Property<short?>("StatusAtMoment")
                        .HasColumnType("smallint")
                        .HasColumnName("status_at_moment");

                    b.HasKey("Id");

                    b.HasIndex("ProtocolId");

                    b.ToTable("t16_protocol_history", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("EventTypeCode")
                        .HasColumnType("smallint")
                        .HasColumnName("event_type_code");

                    b.Property<int>("GlobalSeqInSet")
                        .HasColumnType("integer")
                        .HasColumnName("global_seq_in_set");

                    b.Property<short>("GuestScoreAtMoment")
                        .HasColumnType("smallint")
                        .HasColumnName("guest_score_at_moment");

                    b.Property<short>("HomeScoreAtMoment")
                        .HasColumnType("smallint")
                        .HasColumnName("home_score_at_moment");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<short?>("MinuteMark")
                        .HasColumnType("smallint")
                        .HasColumnName("minute_mark");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("EventTypeCode");

                    b.HasIndex("TeamId");

                    b.HasIndex("MatchId", "SetNumber", "GlobalSeqInSet")
                        .IsUnique();

                    b.ToTable("t17_events", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17aSubstitution", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsLiberoSwap")
                        .HasColumnType("boolean")
                        .HasColumnName("is_libero_swap");

                    b.Property<int>("SubInPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_in_player_id");

                    b.Property<int>("SubOutPlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("sub_out_player_id");

                    b.Property<short?>("SubSeqInSet")
                        .HasColumnType("smallint")
                        .HasColumnName("sub_seq_in_set");

                    b.Property<short?>("SubTypeCode")
                        .HasColumnType("smallint")
                        .HasColumnName("sub_type_code");

                    b.HasKey("EventId");

                    b.HasIndex("SubInPlayerId");

                    b.HasIndex("SubOutPlayerId");

                    b.HasIndex("SubTypeCode");

                    b.ToTable("t17a_substitutions", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17bTimeout", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<short?>("TimeoutSeqInSet")
                        .HasColumnType("smallint")
                        .HasColumnName("timeout_seq_in_set");

                    b.Property<short>("TimeoutTypeCode")
                        .HasColumnType("smallint")
                        .HasColumnName("timeout_type_code");

                    b.HasKey("EventId");

                    b.HasIndex("TimeoutTypeCode");

                    b.ToTable("t17b_timeouts", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T18Sanction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("DelayViolationCode")
                        .HasColumnType("smallint")
                        .HasColumnName("delay_violation_code");

                    b.Property<int?>("DelegationMemberId")
                        .HasColumnType("integer")
                        .HasColumnName("delegation_member_id");

                    b.Property<int?>("EventId")
                        .HasColumnType("integer")
                        .HasColumnName("event_id");

                    b.Property<short>("GuestScoreAtMoment")
                        .HasColumnType("smallint")
                        .HasColumnName("guest_score_at_moment");

                    b.Property<short>("HomeScoreAtMoment")
                        .HasColumnType("smallint")
                        .HasColumnName("home_score_at_moment");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<short>("MemberSeqInMatch")
                        .HasColumnType("smallint")
                        .HasColumnName("member_seq_in_match");

                    b.Property<short?>("MinuteMark")
                        .HasColumnType("smallint")
                        .HasColumnName("minute_mark");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<short>("RecipientTypeCode")
                        .HasColumnType("smallint")
                        .HasColumnName("recipient_type_code");

                    b.Property<short>("SanctionKindCode")
                        .HasColumnType("smallint")
                        .HasColumnName("sanction_kind_code");

                    b.Property<short>("SanctionTypeCode")
                        .HasColumnType("smallint")
                        .HasColumnName("sanction_type_code");

                    b.Property<short>("SetNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("set_number");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("DelayViolationCode");

                    b.HasIndex("MatchId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RecipientTypeCode");

                    b.HasIndex("SanctionKindCode");

                    b.HasIndex("SanctionTypeCode");

                    b.HasIndex("TeamId");

                    b.ToTable("t18_sanctions", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T1Region", b =>
                {
                    b.Property<string>("OktmoCode")
                        .HasColumnType("char(11)")
                        .HasColumnName("oktmo_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("OktmoCode");

                    b.ToTable("t1_regions", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T20Award", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AwardTypeCode")
                        .HasColumnType("smallint")
                        .HasColumnName("award_type_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("AwardTypeCode");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentId");

                    b.ToTable("t20_awards", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T21MatchCaptain", b =>
                {
                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.HasKey("MatchId", "TeamId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("t21_match_captains", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T2Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<int?>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.ToTable("t2_venues", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T3Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("category");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.HasKey("Id");

                    b.ToTable("t3_coaches", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T4Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("HeadCoachId")
                        .HasColumnType("integer")
                        .HasColumnName("head_coach_id");

                    b.Property<int>("HomeVenueId")
                        .HasColumnType("integer")
                        .HasColumnName("home_venue_id");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("name");

                    b.Property<string>("RegionOktmo")
                        .IsRequired()
                        .HasColumnType("char(11)")
                        .HasColumnName("region_oktmo");

                    b.HasKey("Id");

                    b.HasIndex("HeadCoachId");

                    b.HasIndex("HomeVenueId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("RegionOktmo");

                    b.ToTable("t4_teams", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T5Delegation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short?>("AssistantSeqNo")
                        .HasColumnType("smallint")
                        .HasColumnName("assistant_seq_no");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<int>("MatchId")
                        .HasColumnType("integer")
                        .HasColumnName("match_id");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("middle_name");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("role_type");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("TeamId");

                    b.ToTable("t5_delegations", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T6Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<short>("AmpluaCode")
                        .HasColumnType("smallint")
                        .HasColumnName("amplua_code");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("Email")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("first_name");

                    b.Property<short?>("HeightCm")
                        .HasColumnType("smallint")
                        .HasColumnName("height_cm");

                    b.Property<short?>("JerseyNumber")
                        .HasColumnType("smallint")
                        .HasColumnName("jersey_number");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("last_name");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)")
                        .HasColumnName("middle_name");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("phone");

                    b.Property<string>("PhotoUrl")
                        .HasColumnType("text")
                        .HasColumnName("photo_url");

                    b.Property<string>("SportsRank")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("sports_rank");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.Property<int?>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<short?>("WeightKg")
                        .HasColumnType("smallint")
                        .HasColumnName("weight_kg");

                    b.HasKey("Id");

                    b.HasIndex("AmpluaCode");

                    b.HasIndex("StatusCode");

                    b.HasIndex("TeamId");

                    b.ToTable("t6_players", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T7Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<short>("StatusCode")
                        .HasColumnType("smallint")
                        .HasColumnName("status_code");

                    b.Property<DateOnly>("SubmissionDate")
                        .HasColumnType("date")
                        .HasColumnName("submission_date");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.Property<int>("TournamentId")
                        .HasColumnType("integer")
                        .HasColumnName("tournament_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusCode");

                    b.HasIndex("TournamentId");

                    b.HasIndex("TeamId", "TournamentId")
                        .IsUnique();

                    b.ToTable("t7_applications", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T8ApplicationComposition", b =>
                {
                    b.Property<int>("ApplicationId")
                        .HasColumnType("integer")
                        .HasColumnName("application_id");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<bool>("IsLibero")
                        .HasColumnType("boolean")
                        .HasColumnName("is_libero");

                    b.Property<short>("JerseyNumberInApp")
                        .HasColumnType("smallint")
                        .HasColumnName("jersey_number_in_app");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("role");

                    b.HasKey("ApplicationId", "PlayerId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ApplicationId", "JerseyNumberInApp")
                        .IsUnique();

                    b.ToTable("t8_application_composition", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T9Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("name");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("t9_seasons", (string)null);
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T3Coach", "Coach")
                        .WithMany()
                        .HasForeignKey("LinkedCoachId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyballIS.Domain.Entities.T13Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("LinkedOrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("LinkedPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyballIS.Domain.Entities.T12Referee", "Referee")
                        .WithMany()
                        .HasForeignKey("LinkedRefereeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coach");

                    b.Navigation("Organizer");

                    b.Navigation("Player");

                    b.Navigation("Referee");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.R1StartingLineup", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.R2PlayerStats", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.R3Set", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany("Sets")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T10Tournament", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S4TournamentFormat", "Format")
                        .WithMany()
                        .HasForeignKey("FormatCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T13Organizer", "Organizer")
                        .WithMany("Tournaments")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyballIS.Domain.Entities.S18ScoringSystem", "ScoringSystem")
                        .WithMany()
                        .HasForeignKey("ScoringSystemCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T9Season", "Season")
                        .WithMany("Tournaments")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Format");

                    b.Navigation("Organizer");

                    b.Navigation("ScoringSystem");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T11Group", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T10Tournament", "Tournament")
                        .WithMany("Groups")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T14Match", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S17CoinTossOption", "CoinTossChoice")
                        .WithMany()
                        .HasForeignKey("CoinTossChoiceCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "CoinTossWinnerTeam")
                        .WithMany()
                        .HasForeignKey("CoinTossWinnerTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "FirstServeTeam")
                        .WithMany()
                        .HasForeignKey("FirstServeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.T11Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "GuestTeam")
                        .WithMany()
                        .HasForeignKey("GuestTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S5TournamentStage", "Stage")
                        .WithMany()
                        .HasForeignKey("StageCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S6MatchStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T10Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T2Venue", "Venue")
                        .WithMany()
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CoinTossChoice");

                    b.Navigation("CoinTossWinnerTeam");

                    b.Navigation("FirstServeTeam");

                    b.Navigation("Group");

                    b.Navigation("GuestTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Stage");

                    b.Navigation("Status");

                    b.Navigation("Tournament");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T15RefereeAssignment", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T12Referee", "Referee")
                        .WithMany()
                        .HasForeignKey("RefereeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S8RefereeRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Referee");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T16Protocol", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T13Organizer", "Organizer")
                        .WithMany()
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("VolleyballIS.Domain.Entities.S7ProtocolStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Organizer");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T16ProtocolHistory", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T16Protocol", "Protocol")
                        .WithMany("History")
                        .HasForeignKey("ProtocolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Protocol");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17Event", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S9EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("EventType");

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17aSubstitution", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T17Event", "Event")
                        .WithOne("Substitution")
                        .HasForeignKey("VolleyballIS.Domain.Entities.T17aSubstitution", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "SubInPlayer")
                        .WithMany()
                        .HasForeignKey("SubInPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "SubOutPlayer")
                        .WithMany()
                        .HasForeignKey("SubOutPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S10SubstitutionType", "SubType")
                        .WithMany()
                        .HasForeignKey("SubTypeCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("SubInPlayer");

                    b.Navigation("SubOutPlayer");

                    b.Navigation("SubType");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17bTimeout", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T17Event", "Event")
                        .WithOne("Timeout")
                        .HasForeignKey("VolleyballIS.Domain.Entities.T17bTimeout", "EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S11TimeoutType", "TimeoutType")
                        .WithMany()
                        .HasForeignKey("TimeoutTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("TimeoutType");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T18Sanction", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S13DelayViolation", "DelayViolation")
                        .WithMany()
                        .HasForeignKey("DelayViolationCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.S16RecipientType", "RecipientType")
                        .WithMany()
                        .HasForeignKey("RecipientTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S15SanctionKind", "SanctionKind")
                        .WithMany()
                        .HasForeignKey("SanctionKindCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S12SanctionType", "SanctionType")
                        .WithMany()
                        .HasForeignKey("SanctionTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DelayViolation");

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("RecipientType");

                    b.Navigation("SanctionKind");

                    b.Navigation("SanctionType");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T20Award", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S14AwardType", "AwardType")
                        .WithMany()
                        .HasForeignKey("AwardTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("VolleyballIS.Domain.Entities.T10Tournament", "Tournament")
                        .WithMany()
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AwardType");

                    b.Navigation("Player");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T21MatchCaptain", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T4Team", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T3Coach", "HeadCoach")
                        .WithMany("Teams")
                        .HasForeignKey("HeadCoachId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T2Venue", "HomeVenue")
                        .WithMany("HomeTeams")
                        .HasForeignKey("HomeVenueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T1Region", "Region")
                        .WithMany("Teams")
                        .HasForeignKey("RegionOktmo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("HeadCoach");

                    b.Navigation("HomeVenue");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T5Delegation", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T14Match", "Match")
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T6Player", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S1Amplua", "Amplua")
                        .WithMany()
                        .HasForeignKey("AmpluaCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.S2PlayerStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Amplua");

                    b.Navigation("Status");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T7Application", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.S3ApplicationStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T4Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T10Tournament", "Tournament")
                        .WithMany("Applications")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("Team");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T8ApplicationComposition", b =>
                {
                    b.HasOne("VolleyballIS.Domain.Entities.T7Application", "Application")
                        .WithMany("Composition")
                        .HasForeignKey("ApplicationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("VolleyballIS.Domain.Entities.T6Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Application");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T10Tournament", b =>
                {
                    b.Navigation("Applications");

                    b.Navigation("Groups");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T13Organizer", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T14Match", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T16Protocol", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T17Event", b =>
                {
                    b.Navigation("Substitution");

                    b.Navigation("Timeout");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T1Region", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T2Venue", b =>
                {
                    b.Navigation("HomeTeams");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T3Coach", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T7Application", b =>
                {
                    b.Navigation("Composition");
                });

            modelBuilder.Entity("VolleyballIS.Domain.Entities.T9Season", b =>
                {
                    b.Navigation("Tournaments");
                });
#pragma warning restore 612, 618
        }
    }
}
